### PR TITLE
Fix IE8 offset calculation

### LINKED ISSUE #85: document.body.scrollTop is not portable

### PR DESCRIPTION
**Pull request by Abbondanzo**
Closes #85

### CODE REVIEW

File: src/comparisons/elements/offset/ie8.js [hunk 1]
```diff
@@ -1,7 +1,14 @@
 function offset(el) {
+  var docElem = document.documentElement;
   var rect = el.getBoundingClientRect();
   return {
-    top: rect.top + document.body.scrollTop,
-    left: rect.left + document.body.scrollLeft
+    top:
```
Comment (Abbondanzo) [inline src/comparisons/elements/offset/ie8.js:5]: Ripped these conditionals right from source:
https://github.com/jquery/jquery/blob/1.12-stable/src/offset.js
